### PR TITLE
Add message period filter to GNSSStreamer class

### PR DESCRIPTION
**Pull request by acottuli**
# pygnssutils Pull Request Template

## Description

1. Added message period filtering functionality to the `GNSSStreamer` class. This allows you to use a `msgfilter` like `"1006(60),1019(60),1077(10)"` to reduce the output rate of each message type. This is useful when rebroadcasting high-rate RTCM corrections over a low bitrate link (e.g. a satellite link).
2. Added total, filtered, and sent message counters for each message type
2. Modified `gnssserver.py` to allow input from a socket

## Testing

Please test all changes, however trivial, against the supplied unittest suite `tests/test_*.py` e.g. by executing the `tests/testsuite.py` module or using your IDE's native Python unittest integration facilities. Please describe any test cases you have amended or added to this suite to maintain >= 99% code coverage.

- [x] Tested against supplied unittest suite using vscode's Python unittest integration facilities
- [x] Tested new functionality by adding filtered message counters and passing a variety of strings to `--msgfilter`

## Checklist:

- [x] My code follows the style guidelines of this project (see `CONTRIBUTING.MD`).
- [x] I have performed a self-review of my own code.
- [ ] (*if appropriate*) I have cited my u-blox documentation source(s).
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] (*if appropriate*) I have added test cases to the `tests/test_*.py` unittest suite to maintain >= 99% code coverage.
- [x] I have tested my code against the full `tests/test_*.py` unittest suite.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I understand and acknowledge that the code will be published under a BSD 3-Clause license.

### CODE REVIEW

**Comment by semuadmin** [comment]
Hi @acottuli 

Interesting - will review. 

Note that merge is currently blocked as it's unsigned. I can override, but in future can you arrange to GPG-sign all your commits? Many thanks

**Review by semuadmin — COMMENTED** [review]
Hi @acottuli  

No problem with the implementation, and happy to add socket read functionality to gnssserver.py, but I'm a little unclear as to the circumstances in which a message rate filter would be useful? If you're consuming RTCM3 messages from an NTRIP source, for example, would you not need a full complement of messages to effect an RTK correction in the shortest possible time?

Can you provide a couple of specific use cases?

Many thanks.

**Comment by acottuli** [comment]
> Note that merge is currently blocked as it's unsigned. I can override, but in future can you arrange to GPG-sign all your commits? Many thanks

No worries I've amended the commits. It might be worth putting a note about signing commits in your CONTRIBUTING.md as I didn't realise it would be problem until after I made the pull request.

> No problem with the implementation, and happy to add socket read functionality to gnssserver.py, but I'm a little unclear as to the circumstances in which a message rate filter would be useful?

One use case is deformation monitoring in an area where there is no cellular coverage or line of sight between base station and rovers (so receiving RTCM3 corrections over Wi-Fi, LTE or LoRa isn't possible). 

Reducing the RTCM3 MSM message rate from 1Hz to 0.1Hz, reduces data usage by a factor of 10 (which reduces Inmarsat BGAN Link cost from ~$800/month to $180/month) and only has a small effect on the time to first fix and the accuracy of the corrected coordinates.

For a different use case see the quote below from a recent article in GPS world

> There are even some applications for which it is warranted to broadcast corrections at rates slower than 1 Hz. “One example was a user in Japan, where radio links are often throttled to 4800 baud,” said Burnell. “They were looking to see how to slow down corrections to less than 1 Hz so that they could take advantage of multifrequency multi-GNSS RTK.
> [1]https://www.gpsworld.com/high-rate-rtk-helpful-or-hypeful/

**Comment by semuadmin** [comment]
> No worries I've amended the commits. It might be worth putting a note about signing commits in your CONTRIBUTING.md as I didn't realise it would be problem until after I made the pull request.

Fair point - I'd amended CONTRIBUTING.md but hadn't uploaded yet.

**Comment by acottuli** [comment]
Thanks @semuadmin I agree with all the changes you made. 

One minor change I would make is to add the new logging level (3 = DEBUG) to lines 412 & 414 in `gnssserver.py` as currently using the command `gnssserver --verbosity=3` will raise the error `error: argument --verbosity: invalid choice: 3 (choose from 0, 1, 2)`. 

Also, what are you thoughts on making the log `Messages input: X \n Messages filtered: Y \n Messages output: Z \n` output to a log file (or stderr/stdout) at some user-defined frequency (e.g. every 10 minutes) instead of only when the stream is terminated?  It would be useful to have this kind of information logged when monitoring a long-running stream.

**Comment by semuadmin** [comment]
> One minor change I would make is to add the new logging level (3 = DEBUG) to lines 412 & 414 in `gnssserver.py` as currently using the command `gnssserver --verbosity=3` will raise the error `error: argument --verbosity: invalid choice: 3 (choose from 0, 1, 2)`.

Done (sorry about that!) https://github.com/semuconsulting/pygnssutils/commit/ad14d09996e2e4b77fef5069646c80e2ea446b97

> Also, what are you thoughts on making the log `Messages input: X \n Messages filtered: Y \n Messages output: Z \n` output to a log file (or stderr/stdout) at some user-defined frequency (e.g. every 10 minutes) instead of only when the stream is terminated? It would be useful to have this kind of information logged when monitoring a long-running stream.

Not particularly hard to do; you'd need to add a further argument for log output frequency - happy to consider. In the meantime you could probably use a grep at the terminal to achieve a similar end.

**Pull request merged**
